"use client";
import { useEffect, useMemo, useState } from "react";
import { Check, RefreshCw } from "lucide-react";
import { Card, StatusBadge } from "@/components/ui";
import { getTenantClients, type ClientRecord } from "@/lib/client-records";
import { getTenantHouses, type HouseRecord } from "@/lib/house-records";
import { acknowledgeHandover, createHandoverEntry, getRecentHandovers, type HandoverEntry } from "@/lib/handover-records";
const categories = ["participant_update","incident_follow_up","appointment","food_fluid","operational","other"];
export function HandoverWorkspace(){
 const [houses,setHouses]=useState<HouseRecord[]>([]),[clients,setClients]=useState<ClientRecord[]>([]),[entries,setEntries]=useState<HandoverEntry[]>([]);
 const [houseId,setHouseId]=useState(""),[participantId,setParticipantId]=useState(""),[category,setCategory]=useState(categories[0]),[priority,setPriority]=useState<HandoverEntry["priority"]>("routine"),[summary,setSummary]=useState(""),[followUpAction,setFollowUpAction]=useState(""),[message,setMessage]=useState("");
 async function load(){const[h,c,e]=await Promise.all([getTenantHouses(),getTenantClients(),getRecentHandovers(24)]);setHouses(h);setClients(c);setEntries(e);setHouseId(v=>v||h[0]?.id||"");}
 useEffect(()=>{void load();},[]);
 const houseClients=useMemo(()=>clients.filter(c=>!houseId||houses.find(h=>h.id===houseId)?.clientIds.includes(c.id)||c.primaryHouseId===houseId),[clients,houseId,houses]);
 async function save(){if(!houseId||!summary.trim()){setMessage("Choose a house and enter the handover update.");return;}const r=await createHandoverEntry({houseId,participantId,category,priority,summary:summary.trim(),followUpAction:followUpAction.trim()});setMessage(r.saved?"Handover saved.":r.error);if(r.saved){setSummary("");setFollowUpAction("");await load();}}
 return <div className="space-y-6"><Card><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-semibold uppercase tracking-wide text-sea">Communication book</p><h2 className="mt-1 text-xl font-semibold text-ink">Add handover</h2><p className="mt-2 text-sm text-slate-600">Share a concise update with the next team. Use incidents and progress notes for full records.</p></div><StatusBadge label="House scoped" tone="green" /></div>
 <div className="mt-5 grid gap-3 md:grid-cols-2 lg:grid-cols-4"><label className="text-sm font-semibold text-slate-700">House/service<select className="mt-2 w-full rounded-md border border-slate-300 bg-white p-3" value={houseId} onChange={e=>{setHouseId(e.target.value);setParticipantId("");}}><option value="">Select house</option>{houses.map(h=><option key={h.id} value={h.id}>{h.name}</option>)}</select></label><label className="text-sm font-semibold text-slate-700">Client, if relevant<select className="mt-2 w-full rounded-md border border-slate-300 bg-white p-3" value={participantId} onChange={e=>setParticipantId(e.target.value)}><option value="">House-wide</option>{houseClients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="text-sm font-semibold text-slate-700">Category<select className="mt-2 w-full rounded-md border border-slate-300 bg-white p-3" value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select></label><label className="text-sm font-semibold text-slate-700">Priority<select className="mt-2 w-full rounded-md border border-slate-300 bg-white p-3" value={priority} onChange={e=>setPriority(e.target.value as HandoverEntry["priority"])}><option>routine</option><option>important</option><option>urgent</option></select></label></div>
 <label className="mt-4 block text-sm font-semibold text-slate-700">Update<textarea className="mt-2 min-h-28 w-full rounded-md border border-slate-300 p-3" value={summary} onChange={e=>setSummary(e.target.value)} /></label><label className="mt-3 block text-sm font-semibold text-slate-700">Follow-up action, if required<input className="mt-2 w-full rounded-md border border-slate-300 p-3" value={followUpAction} onChange={e=>setFollowUpAction(e.target.value)} /></label><button type="button" onClick={()=>void save()} className="mt-4 min-h-11 rounded-md bg-ink px-4 text-sm font-semibold text-white">Save handover</button>{message?<p aria-live="polite" className="mt-3 text-sm font-semibold text-slate-700">{message}</p>:null}</Card>
 <Card><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-semibold uppercase tracking-wide text-sea">Incoming shift</p><h2 className="mt-1 text-xl font-semibold text-ink">Last 24 hours</h2></div><button type="button" onClick={()=>void load()} className="grid h-10 w-10 place-items-center rounded-md border border-slate-300" aria-label="Refresh handover"><RefreshCw size={18}/></button></div><div className="mt-4 space-y-3">{!entries.length?<p className="rounded-md border border-dashed border-slate-300 p-4 text-sm text-slate-600">No handover entries in the last 24 hours.</p>:entries.map(entry=>{const client=clients.find(c=>c.id===entry.participantId),house=houses.find(h=>h.id===entry.houseId);return <article key={entry.id} className="rounded-md border border-slate-200 p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-semibold text-ink">{client?.name||house?.name||"House update"}</p><p className="text-xs text-slate-500">{new Date(entry.createdAt).toLocaleString("en-AU")} · {entry.category.replaceAll("_"," ")}</p></div><StatusBadge label={entry.priority} tone={entry.priority==="urgent"?"red":entry.priority==="important"?"amber":"blue"}/></div><p className="mt-3 text-sm leading-6 text-slate-700">{entry.summary}</p>{entry.followUpAction?<p className="mt-2 rounded-md bg-amber-50 px-3 py-2 text-sm text-amber-900"><strong>Follow-up:</strong> {entry.followUpAction}</p>:null}<button disabled={entry.acknowledged} type="button" onClick={async()=>{await acknowledgeHandover(entry);await load();}} className="mt-3 inline-flex min-h-10 items-center gap-2 rounded-md bg-teal-700 px-3 text-sm font-semibold text-white disabled:bg-slate-300"><Check size={16}/>{entry.acknowledged?"Read":"Mark as read"}</button></article>;})}</div></Card></div>;
}
