import type { MarketingEventName, Attribution } from "@/lib/marketing/types";
import { classifyMarketingSource } from "@/lib/marketing/attribution";
const visitorCookie="empower_visitor_id",sessionCookie="empower_session_id",touchKey="empowernotes:first-attribution",sessionTimeKey="empowernotes:marketing-session-at";const sessionMs=30*60*1000;
export function marketingEnabled(){return process.env.NEXT_PUBLIC_MARKETING_ATTRIBUTION_ENABLED==="true"}
export function getMarketingIdentity(){if(typeof window==="undefined")return{visitorId:"",sessionId:"",attribution:null as Attribution|null};let visitorId=readCookie(visitorCookie),sessionId=readCookie(sessionCookie);const last=Number(sessionStorage.getItem(sessionTimeKey)||0);if(!visitorId){visitorId=crypto.randomUUID();writeCookie(visitorCookie,visitorId,15552000)}if(!sessionId||Date.now()-last>sessionMs){sessionId=crypto.randomUUID();writeCookie(sessionCookie,sessionId,1800)}sessionStorage.setItem(sessionTimeKey,String(Date.now()));const attribution=captureAttribution();return{visitorId,sessionId,attribution}}
export async function trackMarketingEvent(eventName:MarketingEventName,metadata:Record<string,string|number|boolean>={}){if(!marketingEnabled()||typeof window==="undefined")return;const identity=getMarketingIdentity();await fetch("/api/marketing/events",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...identity,eventName,path:window.location.pathname,metadata}),keepalive:true}).catch(()=>undefined)}
export function getMarketingVisitorId(){return marketingEnabled()?getMarketingIdentity().visitorId:""}
function captureAttribution():Attribution{const params=new URLSearchParams(location.search);const current:Attribution={utmSource:params.get("utm_source")||"",utmMedium:params.get("utm_medium")||"",utmCampaign:params.get("utm_campaign")||"",utmContent:params.get("utm_content")||"",utmTerm:params.get("utm_term")||"",gclid:params.get("gclid")||"",oppref:params.get("oppref")||"",referrer:isExternalReferrer(document.referrer)?document.referrer:"",landingPath:location.pathname,sourceClass:"direct"};current.sourceClass=classifyMarketingSource(current);let first:Attribution|null=null;try{first=JSON.parse(localStorage.getItem(touchKey)||"null") as Attribution|null}catch{}if(!first){first=current;localStorage.setItem(touchKey,JSON.stringify(first))}return current.sourceClass==="direct"&&first?first:current}
function isExternalReferrer(value:string){if(!value)return false;try{return new URL(value).origin!==location.origin}catch{return false}}
function readCookie(name:string){return document.cookie.split("; ").find(x=>x.startsWith(`${name}=`))?.split("=").slice(1).join("=")||""}function writeCookie(name:string,value:string,maxAge:number){document.cookie=`${name}=${encodeURIComponent(value)}; Path=/; Max-Age=${maxAge}; SameSite=Lax${location.protocol==="https:"?"; Secure":""}`}
